ct2_model_path: ct2/ct2-nllb-200-3.3B-no-quant
sp_model_path: sp/sentencepiece.bpe.model

batch_size: 1024
beam_size: 3
testset:
  en-am:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: amh_Ethi
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: amh_Ethi
    comet_model_name: masakhane/africomet-mtl
  am-en:
    dataset:
      path: facebook/flores
      src_config: amh_Ethi
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: amh_Ethi
    tgt_lang: eng_Latn
    comet_model_name: masakhane/africomet-mtl
  en-sw:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: swh_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: swh_Latn
    comet_model_name: masakhane/africomet-mtl
  sw-en:
    dataset:
      path: facebook/flores
      src_config: swh_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: swh_Latn
    tgt_lang: eng_Latn
    comet_model_name: masakhane/africomet-mtl
  en-ha:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: hau_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: hau_Latn
    comet_model_name: masakhane/africomet-mtl
  ha-en:
    dataset:
      path: facebook/flores
      src_config: hau_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: hau_Latn
    tgt_lang: eng_Latn
    comet_model_name: masakhane/africomet-mtl
  en-zu:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: zul_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: zul_Latn
    comet_model_name: masakhane/africomet-mtl
  zu-en:
    dataset:
      path: facebook/flores
      src_config: zul_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: zul_Latn
    tgt_lang: eng_Latn
    comet_model_name: masakhane/africomet-mtl
  en-so:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: som_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: som_Latn
    comet_model_name: masakhane/africomet-mtl
  so-en:
    dataset:
      path: facebook/flores
      src_config: som_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: som_Latn
    tgt_lang: eng_Latn
    comet_model_name: masakhane/africomet-mtl
  en-yo:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: yor_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: yor_Latn
    comet_model_name: masakhane/africomet-mtl
  yo-en:
    dataset:
      path: facebook/flores
      src_config: yor_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: yor_Latn
    tgt_lang: eng_Latn
    comet_model_name: masakhane/africomet-mtl
  en-af:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: afr_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: afr_Latn
    comet_model_name: masakhane/africomet-mtl
  af-en:
    dataset:
      path: facebook/flores
      src_config: afr_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: afr_Latn
    tgt_lang: eng_Latn
    comet_model_name: masakhane/africomet-mtl
  en-ar:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: arb_Arab
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: arb_Arab
    comet_model_name: Unbabel/wmt22-comet-da
  ar-en:
    dataset:
      path: facebook/flores
      src_config: arb_Arab
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: arb_Arab
    tgt_lang: eng_Latn
    comet_model_name: Unbabel/wmt22-comet-da
  en-arz:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: arz_Arab
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: arz_Arab
    comet_model_name: Unbabel/wmt22-comet-da
  arz-en:
    dataset:
      path: facebook/flores
      src_config: arz_Arab
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: arz_Arab
    tgt_lang: eng_Latn
    comet_model_name: Unbabel/wmt22-comet-da
  en-fr:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: fra_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: fra_Latn
    comet_model_name: Unbabel/wmt22-comet-da
  fr-en:
    dataset:
      path: facebook/flores
      src_config: fra_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: fra_Latn
    tgt_lang: eng_Latn
    comet_model_name: Unbabel/wmt22-comet-da
  en-es:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: spa_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: spa_Latn
    comet_model_name: Unbabel/wmt22-comet-da
  es-en:
    dataset:
      path: facebook/flores
      src_config: spa_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: spa_Latn
    tgt_lang: eng_Latn
    comet_model_name: Unbabel/wmt22-comet-da
  en-pt:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: por_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: por_Latn
    comet_model_name: Unbabel/wmt22-comet-da
  pt-en:
    dataset:
      path: facebook/flores
      src_config: por_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: por_Latn
    tgt_lang: eng_Latn
    comet_model_name: Unbabel/wmt22-comet-da
  fr-wo:
    dataset:
      path: facebook/flores
      src_config: fra_Latn
      tgt_config: wol_Latn
      text_col: sentence
      split: devtest
    src_lang: fra_Latn
    tgt_lang: wol_Latn
    comet_model_name: masakhane/africomet-mtl
  wo-fr:
    dataset:
      path: facebook/flores
      src_config: wol_Latn
      tgt_config: fra_Latn
      text_col: sentence
      split: devtest
    src_lang: wol_Latn
    tgt_lang: fra_Latn
    comet_model_name: masakhane/africomet-mtl
  fr-ln:
    dataset: 
      path: facebook/flores
      src_config: fra_Latn
      tgt_config: lin_Latn
      text_col: sentence
      split: devtest
    src_lang: fra_Latn
    tgt_lang: lin_Latn
    comet_model_name: masakhane/africomet-mtl
  ln-fr:
    dataset:
      path: facebook/flores
      src_config: lin_Latn
      tgt_config: fra_Latn
      text_col: sentence
      split: devtest
    src_lang: lin_Latn
    tgt_lang: fra_Latn
    comet_model_name: masakhane/africomet-mtl

  

logging:
logging:
  debug: true
  log_dir: "logs/"
  log_file: "nllb-200-3.3B-no-quant-eval.log"
  results_file: "results/nllb-200-3.3B-no-quant-eval-results.json"
  evaluation_summary_file: "results/nllb-200-3.3B-no-quant-eval-summary.csv"