ct2_model_path: ct2/ct2-nllb-200-3.3B-no-quantization
sp_model_path: sp/sentencepiece.bpe.model
comet_model_name: masakhane/africomet-mtl
batch_size: 16
beam_size: 2
testset:
  en-am:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: amh_Ethi
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: amh_Ethi
  am-en:
    dataset:
      path: facebook/flores
      src_config: amh_Ethi
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: amh_Ethi
    tgt_lang: eng_Latn
  en-sw:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: swh_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: swh_Latn
  sw-en:
    dataset:
      path: facebook/flores
      src_config: swh_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: swh_Latn
    tgt_lang: eng_Latn
  en-ha:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: hau_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: hau_Latn
  ha-en:
    dataset:
      path: facebook/flores
      src_config: hau_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: hau_Latn
    tgt_lang: eng_Latn
  en-zu:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: zul_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: zul_Latn
  zu-en:
    dataset:
      path: facebook/flores
      src_config: zul_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: zul_Latn
    tgt_lang: eng_Latn
  en-so:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: som_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: som_Latn
  so-en:
    dataset:
      path: facebook/flores
      src_config: som_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: som_Latn
    tgt_lang: eng_Latn
  en-yo:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: yor_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: yor_Latn
  yo-en:
    dataset:
      path: facebook/flores
      src_config: yor_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: yor_Latn
    tgt_lang: eng_Latn
  en-af:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: afr_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: afr_Latn
  af-en:
    dataset:
      path: facebook/flores
      src_config: afr_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: afr_Latn
    tgt_lang: eng_Latn
  en-ar:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: arb_Arab
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: arb_Arab
  ar-en:
    dataset:
      path: facebook/flores
      src_config: arb_Arab
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: arb_Arab
    tgt_lang: eng_Latn
  en-arz:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: arz_Arab
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: arz_Arab
  arz-en:
    dataset:
      path: facebook/flores
      src_config: arz_Arab
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: arz_Arab
    tgt_lang: eng_Latn
  en-fr:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: fra_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: fra_Latn
  fr-en:
    dataset:
      path: facebook/flores
      src_config: fra_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: fra_Latn
    tgt_lang: eng_Latn
  en-es:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: spa_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: spa_Latn
  es-en:
    dataset:
      path: facebook/flores
      src_config: spa_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: spa_Latn
    tgt_lang: eng_Latn
  en-pt:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: por_Latn
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: por_Latn
  pt-en:
    dataset:
      path: facebook/flores
      src_config: por_Latn
      tgt_config: eng_Latn
      text_col: sentence
      split: devtest
    src_lang: por_Latn
    tgt_lang: eng_Latn
  fr-wo:
    dataset:
      path: facebook/flores
      src_config: fra_Latn
      tgt_config: wol_Latn
      text_col: sentence
      split: devtest
    src_lang: fra_Latn
    tgt_lang: wol_Latn
  wo-fr:
    dataset:
      path: facebook/flores
      src_config: wol_Latn
      tgt_config: fra_Latn
      text_col: sentence
      split: devtest
    src_lang: wol_Latn
    tgt_lang: fra_Latn
  fr-ln:
    dataset: 
      path: facebook/flores
      src_config: fra_Latn
      tgt_config: lin_Latn
      text_col: sentence
      split: devtest
    src_lang: fra_Latn
    tgt_lang: lin_Latn
  ln-fr:
    dataset:
      path: facebook/flores
      src_config: lin_Latn
      tgt_config: fra_Latn
      text_col: sentence
      split: devtest
    src_lang: lin_Latn
    tgt_lang: fra_Latn
  

logging:
  debug: true
  log_dir: "logs/"
  log_file: nllb-200-3.3B-no-quantization-eval.log