ct2_model_path: ct2/ct2-nllb-200-600m-no-qunat
sp_model_path: sp/sentencepiece.bpe.model
comet_model_name: masakhane/africomet-mtl
batch_size: 4
beam_size: 2
testset:
  en-am:
    dataset:
      path: facebook/flores
      src_config: eng_Latn
      tgt_config: amh_Ethi
      text_col: sentence
      split: devtest
    src_lang: eng_Latn
    tgt_lang: amh_Ethi
logging:
  debug: true
  log_dir: "logs/"
  log_file: nllb-200-3.3B-no-quantization-eval.log